"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Users, Briefcase, Scale, Settings, Search, Plus, Mail, Phone, Pencil, X } from "lucide-react";
import { type CompanyUserProfile, formatCompanyBusinessArea, formatCompanyUserRole } from "@/types/user";
import { UserToggleStatusButton } from "@/components/users/user-toggle-status-button";
import { ManagementMetric } from "./management-ui";
import { ManagementPagination } from "./management-pagination";
import { formatDateTime } from "@/lib/clients/formatters";

export function ManagementTeam({ users, initialStatus = "", role, licenseLimit, createBlocked }: { users: CompanyUserProfile[]; initialStatus?: string; role: string | null; licenseLimit: number; createBlocked: boolean }) {
  const [query, setQuery] = useState("");
  const [area, setArea] = useState("");
  const [status, setStatus] = useState(initialStatus);
  const [selection, setSelectedId] = useState<string | null>(users.find(user => !initialStatus || user.is_active === (initialStatus === "active"))?.id ?? null);
  const [pageState, setPage] = useState({ number: 1, filter: "" });
  const filter = `${query}|${area}|${status}`;
  const filtered = useMemo(() => users.filter(user => (!query || [user.full_name, user.nickname, user.username, user.email].some(value => value?.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))) && (!area || (area === "management" ? user.role === "admin" || user.role === "manager" : user.role === "seller" && (area === "commercial" ? user.business_area !== "legal" : user.business_area === "legal"))) && (!status || user.is_active === (status === "active"))), [users, query, area, status]);
  const page = pageState.filter === filter ? Math.min(pageState.number, Math.max(1, Math.ceil(filtered.length / 8))) : 1;
  const visible = filtered.slice((page - 1) * 8, page * 8);
  const selectedId = selection === null ? null : visible.find(user => user.id === selection)?.id ?? visible[0]?.id ?? null;
  const selected = users.find(user => user.id === selectedId);
  const active = users.filter(user => user.is_active).length;
  const canEdit = (user: CompanyUserProfile) => role === "admin" || (role === "manager" && user.role === "seller");
  return <div className="management-page space-y-4">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ManagementMetric label="Usuários ativos" value={active} detail={`${active} de ${licenseLimit} licenças`} icon={Users} /><ManagementMetric label="Comercial" value={users.filter(user => user.role === "seller" && user.business_area !== "legal").length} icon={Briefcase} /><ManagementMetric label="Jurídico" value={users.filter(user => user.role === "seller" && user.business_area === "legal").length} icon={Scale} /><ManagementMetric label="Gestão" value={users.filter(user => user.role === "admin" || user.role === "manager").length} icon={Settings} tone="success" /></div>
    <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_300px]">
      <section className="min-w-0 overflow-hidden rounded-lg border border-[var(--ns-border)] bg-[var(--ns-surface)]">
        <div className="flex flex-wrap items-center gap-3 border-b border-[var(--ns-border)] p-3"><label className="relative min-w-48 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--ns-text-secondary)]" /><input aria-label="Buscar equipe" placeholder="Buscar por nome, e-mail ou login" value={query} onChange={event => setQuery(event.target.value)} className="w-full rounded border border-[var(--ns-border)] bg-[var(--ns-surface)] py-2.5 pl-9 pr-3 text-sm" /></label><select aria-label="Área da equipe" value={area} onChange={event => setArea(event.target.value)} className="rounded border border-[var(--ns-border)] p-2 text-sm"><option value="">Todas as áreas</option><option value="commercial">Comercial</option><option value="legal">Jurídico</option><option value="management">Gestão</option></select><select aria-label="Status da equipe" value={status} onChange={event => setStatus(event.target.value)} className="rounded border border-[var(--ns-border)] p-2 text-sm"><option value="">Todos os status</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select>{!createBlocked && <Link href="/usuarios/novo" className="flex items-center gap-2 rounded bg-[var(--ns-primary)] px-3 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Novo usuário</Link>}</div>
        <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead><tr>{["Nome", "Área", "Perfil", "Status", "Meta mensal", "Ações"].map(label => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{visible.map(user => <tr key={user.id} tabIndex={0} aria-label={`Ver usuário ${user.full_name ?? user.username}`} onMouseEnter={() => setSelectedId(user.id)} onFocus={() => setSelectedId(user.id)} onClick={() => setSelectedId(user.id)} onKeyDown={event => { if (event.key === "Enter") setSelectedId(user.id); }} className={`cursor-pointer border-t border-[var(--ns-border)] ${selectedId === user.id ? "management-selected" : ""}`}><td className="px-3 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[var(--ns-primary)] font-semibold text-white">{(user.full_name ?? user.username ?? "U").split(" ").slice(0, 2).map(word => word[0]).join("")}</span><div><strong>{user.full_name ?? user.username}</strong><p className="mt-1 text-[var(--ns-text-secondary)]">{user.email ?? user.username}</p></div></div></td><td className="px-3 py-4">{user.role !== "seller" ? "Gestão" : formatCompanyBusinessArea(user.business_area)}</td><td className="px-3 py-4">{formatCompanyUserRole(user.role)}</td><td className="px-3 py-4"><span className={`management-badge ${user.is_active ? "success" : "danger"}`}>{user.is_active ? "Ativo" : "Inativo"}</span></td><td className="px-3 py-4">{user.monthly_goal ? Number(user.monthly_goal).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : "Não definida"}</td><td className="px-3 py-4">{canEdit(user) ? <Link aria-label={`Editar ${user.full_name}`} href={`/usuarios/${user.id}/editar`} className="inline-flex rounded border border-[var(--ns-border)] p-2 text-[var(--ns-primary)]"><Pencil className="h-4 w-4" /></Link> : "Somente leitura"}</td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-sm text-[var(--ns-text-secondary)]">Nenhum usuário encontrado.</p>}</div>
        <ManagementPagination page={page} count={filtered.length} pageSize={8} onChange={number => setPage({ number, filter })} />
      </section>
      {selected && <aside className="rounded-lg xl:sticky xl:top-4 xl:max-h-[calc(100dvh-2rem)] xl:overflow-y-auto border border-[var(--ns-border)] bg-[var(--ns-surface)] p-4"><div className="flex items-start justify-between gap-2"><div><h2 className="font-semibold">{selected.full_name ?? selected.username}</h2><p className="mt-1 text-xs text-[var(--ns-text-secondary)]">{formatCompanyUserRole(selected.role)}</p></div><button type="button" aria-label="Fechar detalhes do usuário" onClick={() => setSelectedId(null)}><X className="h-4 w-4" /></button></div><div className="mt-5 flex gap-3">{selected.email && <a title="Enviar e-mail" href={`mailto:${selected.email}`} className="rounded border border-[var(--ns-border)] p-3"><Mail className="h-5 w-5" /></a>}{selected.phone && <a title="Abrir atendimento" href={`/atendimento?telefone=${selected.phone.replace(/\D/g, "")}`} className="rounded border border-[var(--ns-border)] p-3"><Phone className="h-5 w-5" /></a>}{canEdit(selected) && <Link title="Editar usuário" href={`/usuarios/${selected.id}/editar`} className="rounded border border-[var(--ns-border)] p-3"><Pencil className="h-5 w-5" /></Link>}</div><dl className="mt-5 space-y-4 border-t border-[var(--ns-border)] pt-4 text-xs">{[{ label: "E-mail", value: selected.email }, { label: "Login", value: selected.username }, { label: "Telefone", value: selected.phone }, { label: "Área", value: formatCompanyBusinessArea(selected.business_area) }, { label: "Cadastrado em", value: formatDateTime(selected.created_at) }].map(item => <div key={item.label}><dt className="text-[var(--ns-text-secondary)]">{item.label}</dt><dd className="mt-1 break-words">{item.value ?? "Não informado"}</dd></div>)}</dl>{canEdit(selected) && <div className="mt-5 border-t border-[var(--ns-border)] pt-4"><UserToggleStatusButton userId={selected.id} isActive={selected.is_active} /></div>}</aside>}
    </div>
  </div>;
}
