"use client";

import { useState } from "react";
import { FileText, MessageSquareText } from "lucide-react";
import Link from "next/link";
import { ClientApprovalQueue, type DocumentApprovalQueueItem, type TrackingApprovalQueueItem } from "@/components/approvals/client-approval-queue";
import { formatDateTime } from "@/lib/clients/formatters";

export function ManagementApprovals({ trackingItems, documentItems }: { trackingItems: TrackingApprovalQueueItem[]; documentItems: DocumentApprovalQueueItem[] }) {
  const rows = [...trackingItems.map(item => ({ ...item, key: `tracking:${item.id}`, type: "Acompanhamento" })), ...documentItems.map(item => ({ ...item, key: `document:${item.id}`, type: "Documento" }))].sort((a, b) => b.requestedAt.localeCompare(a.requestedAt));
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("");
  const [selectedKey, setSelectedKey] = useState(rows[0]?.key ?? "");
  const visible = rows.filter(row => (!filter || row.type === filter) && `${row.title} ${row.clientName} ${row.requestedBy}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  const selected = visible.find(row => row.key === selectedKey) ?? visible[0];
  return <div className="management-page space-y-4"><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_410px]">
    <section className="min-w-0 rounded-lg border border-[var(--ns-border)] bg-[var(--ns-surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold">Aprovações pendentes · {rows.length}</h2><input aria-label="Buscar aprovações" value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar cliente, conteúdo ou responsável" className="rounded border border-[var(--ns-border)] px-3 py-2 text-xs" /></div><select aria-label="Tipo de aprovação" value={filter} onChange={event => setFilter(event.target.value)} className="my-3 rounded border border-[var(--ns-border)] px-3 py-2 text-xs"><option value="">Todos os tipos</option><option>Acompanhamento</option><option>Documento</option></select><div className="overflow-x-auto"><table className="w-full min-w-[500px] text-left text-xs"><thead><tr>{["Tipo", "Cliente / Conteúdo", "Responsável", "Solicitado em"].map(label => <th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{visible.map(row => <tr key={row.key} tabIndex={0} aria-label={`Revisar ${row.title}`} onClick={() => setSelectedKey(row.key)} onKeyDown={event => { if (event.key === "Enter") setSelectedKey(row.key); }} className={`cursor-pointer border-t border-[var(--ns-border)] ${selected?.key === row.key ? "management-selected" : ""}`}><td className="p-3">{row.type === "Documento" ? <FileText className="h-5 w-5 text-[var(--ns-primary)]" /> : <MessageSquareText className="h-5 w-5 text-[var(--ns-primary)]" />}<span className="mt-1 block">{row.type}</span></td><td className="p-3"><strong>{row.title}</strong><span className="mt-1 block text-[var(--ns-text-secondary)]">{row.clientName}</span></td><td className="p-3">{row.requestedBy}</td><td className="p-3">{formatDateTime(row.requestedAt)}</td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-sm text-[var(--ns-text-secondary)]">Nenhuma solicitação pendente para estes filtros.</p>}</div></section>
    <aside className="management-approval-detail min-w-0 xl:sticky xl:top-4"><h2 className="mb-3 text-sm font-semibold">Detalhes da aprovação</h2>{selected ? <ClientApprovalQueue key={selected.key} compact trackingItems={selected.type === "Acompanhamento" ? trackingItems.filter(item => item.id === selected.id) : []} documentItems={selected.type === "Documento" ? documentItems.filter(item => item.id === selected.id) : []} /> : <p className="text-sm text-[var(--ns-text-secondary)]">Sem solicitações para revisar.</p>}</aside>
  </div><div className="grid gap-4 sm:grid-cols-2"><section className="rounded-lg border border-[var(--ns-border)] bg-[var(--ns-surface)] p-4"><h2 className="mb-4 text-sm font-semibold">Templates rápidos</h2><div className="flex flex-wrap gap-3"><Link href="/documentos/templates" className="text-sm text-[var(--ns-primary)]">Templates de documentos</Link><Link href="/emails/templates" className="text-sm text-[var(--ns-primary)]">Comunicação ao cliente</Link></div></section><section className="rounded-lg border border-[var(--ns-border)] bg-[var(--ns-surface)] p-4"><h2 className="mb-4 text-sm font-semibold">Operação</h2><div className="flex flex-wrap gap-3"><Link href="/contratos" className="text-sm text-[var(--ns-primary)]">Contratos gerados</Link><Link href="/empresa" className="text-sm text-[var(--ns-primary)]">Configurações da empresa</Link></div></section></div></div>;
}
